W1202 09:43:16.394000 3840729 site-packages/torch/distributed/run.py:793] 
W1202 09:43:16.394000 3840729 site-packages/torch/distributed/run.py:793] *****************************************
W1202 09:43:16.394000 3840729 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1202 09:43:16.394000 3840729 site-packages/torch/distributed/run.py:793] *****************************************
DeviceMesh('cuda', [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]], mesh_dim_names=('pp', 'tp'))
DeviceMesh('cuda', [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]], mesh_dim_names=('pp', 'tp'))
DeviceMesh('cuda', [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]], mesh_dim_names=('pp', 'tp'))
DeviceMesh('cuda', [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]], mesh_dim_names=('pp', 'tp'))
DeviceMesh('cuda', [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]], mesh_dim_names=('pp', 'tp'))
DeviceMesh('cuda', [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]], mesh_dim_names=('pp', 'tp'))
DeviceMesh('cuda', [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]], mesh_dim_names=('pp', 'tp'))
DeviceMesh('cuda', [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]], mesh_dim_names=('pp', 'tp'))
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-package self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
[rank8]: Traceback (most recent call last):
[rank8]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
[rank8]:     main(
[rank8]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 622, in main
[rank8]:     y, decode_latency, prefill_latency = generate(
[rank8]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank8]:     return func(*args, **kwargs)
[rank8]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 328, in generate
[rank8]:     send_recv(send_list=[], recv_list=[prefill_intermediate])
[rank8]:   File "/home/charlie/skip-residual/gpt-fast/gpt_fast/utils.py", line 436, in send_recv
[rank8]:     works = dist.batch_isend_irecv(ops)
[rank8]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2567, in batch_isend_irecv
[rank8]:     p2p_op.op(p2p_op.tensor, p2p_op.peer, p2p_op.group, p2p_op.tag)
[rank8]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2305, in irecv
[rank8]:     return pg.recv([tensor], group_src_rank, tag)
[rank8]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[rank8]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[rank8]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x14a2194f9106 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank8]: frame #1: <unknown function> + 0x62f51d8 (0x14a254dd11d8 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x367 (0x14a254dcdf57 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x2a (0x14a254dce2da in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #4: c10d::TCPStore::get(std::string const&) + 0x7a (0x14a254dcf07a in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14a254d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14a254d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14a254d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14a254d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x14a21a7d681f in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank8]: frame #10: c10d::ProcessGroupNCCL::initNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x10c6 (0x14a21a7e4386 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank8]: frame #11: c10d::ProcessGroupNCCL::recv(std::vector<at::Tensor, std::allocator<at::Tensor> >&, int, int) + 0x16c4 (0x14a21a803404 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank8]: frame #12: <unknown function> + 0x62927f9 (0x14a254d6e7f9 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #13: <unknown function> + 0x629d1ea (0x14a254d791ea in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #14: <unknown function> + 0x58a83bb (0x14a2543843bb in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #15: <unknown function> + 0x58a5c39 (0x14a254381c39 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #16: <unknown function> + 0x1aa3808 (0x14a25057f808 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #17: <unknown function> + 0x62a60c4 (0x14a254d820c4 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #18: <unknown function> + 0x62ab341 (0x14a254d87341 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank8]: frame #19: <unknown function> + 0xdfdbae (0x14a264b81bae in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank8]: frame #20: <unknown function> + 0x4d9367 (0x14a26425d367 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank8]: frame #21: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x4fdc87]
[rank8]: frame #22: _PyObject_MakeTpCall + 0x25b (0x4f741b in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #23: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x509cbf]
[rank8]: frame #24: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #25: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #26: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #27: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #28: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #29: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #30: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #31: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #32: PyObject_Call + 0xb8 (0x50a508 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #33: _PyEval_EvalFrameDefault + 0x2b79 (0x4f0c69 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #34: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #35: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #36: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #37: _PyEval_EvalFrameDefault + 0x31f (0x4ee40f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #38: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5950f2]
[rank8]: frame #39: PyEval_EvalCode + 0x87 (0x595037 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #40: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c5e67]
[rank8]: frame #41: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c0fb0]
[rank8]: frame #42: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x45970e]
[rank8]: frame #43: _PyRun_SimpleFileObject + 0x19f (0x5bb53f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #44: _PyRun_AnyFileObject + 0x43 (0x5bb2a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #45: Py_RunMain + 0x38d (0x5b805d in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #46: Py_BytesMain + 0x39 (0x588679 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank8]: frame #47: <unknown function> + 0x29d90 (0x14a266456d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank8]: frame #48: __libc_start_main + 0x80 (0x14a266456e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank8]: frame #49: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x58852e]
[rank8]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank12]: Traceback (most recent call last):
[rank12]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
[rank12]:     main(
[rank12]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 622, in main
[rank12]:     y, decode_latency, prefill_latency = generate(
[rank12]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank12]:     return func(*args, **kwargs)
[rank12]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 328, in generate
[rank12]:     send_recv(send_list=[], recv_list=[prefill_intermediate])
[rank12]:   File "/home/charlie/skip-residual/gpt-fast/gpt_fast/utils.py", line 436, in send_recv
[rank12]:     works = dist.batch_isend_irecv(ops)
[rank12]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2567, in batch_isend_irecv
[rank12]:     p2p_op.op(p2p_op.tensor, p2p_op.peer, p2p_op.group, p2p_op.tag)
[rank12]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2305, in irecv
[rank12]:     return pg.recv([tensor], group_src_rank, tag)
[rank12]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[rank12]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[rank12]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x14bea196c106 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank12]: frame #1: <unknown function> + 0x62f51d8 (0x14be911d11d8 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x367 (0x14be911cdf57 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x2a (0x14be911ce2da in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #4: c10d::TCPStore::get(std::string const&) + 0x7a (0x14be911cf07a in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14be9117c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14be9117c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14be9117c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14be9117c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x14be56bd681f in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank12]: frame #10: c10d::ProcessGroupNCCL::initNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x10c6 (0x14be56be4386 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank12]: frame #11: c10d::ProcessGroupNCCL::recv(std::vector<at::Tensor, std::allocator<at::Tensor> >&, int, int) + 0x16c4 (0x14be56c03404 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank12]: frame #12: <unknown function> + 0x62927f9 (0x14be9116e7f9 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #13: <unknown function> + 0x629d1ea (0x14be911791ea in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #14: <unknown function> + 0x58a83bb (0x14be907843bb in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #15: <unknown function> + 0x58a5c39 (0x14be90781c39 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #16: <unknown function> + 0x1aa3808 (0x14be8c97f808 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #17: <unknown function> + 0x62a60c4 (0x14be911820c4 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #18: <unknown function> + 0x62ab341 (0x14be91187341 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank12]: frame #19: <unknown function> + 0xdfdbae (0x14bea0f81bae in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank12]: frame #20: <unknown function> + 0x4d9367 (0x14bea065d367 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank12]: frame #21: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x4fdc87]
[rank12]: frame #22: _PyObject_MakeTpCall + 0x25b (0x4f741b in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #23: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x509cbf]
[rank12]: frame #24: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #25: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #26: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #27: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #28: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #29: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #30: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #31: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #32: PyObject_Call + 0xb8 (0x50a508 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #33: _PyEval_EvalFrameDefault + 0x2b79 (0x4f0c69 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #34: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #35: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #36: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #37: _PyEval_EvalFrameDefault + 0x31f (0x4ee40f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #38: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5950f2]
[rank12]: frame #39: PyEval_EvalCode + 0x87 (0x595037 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #40: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c5e67]
[rank12]: frame #41: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c0fb0]
[rank12]: frame #42: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x45970e]
[rank12]: frame #43: _PyRun_SimpleFileObject + 0x19f (0x5bb53f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #44: _PyRun_AnyFileObject + 0x43 (0x5bb2a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #45: Py_RunMain + 0x38d (0x5b805d in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #46: Py_BytesMain + 0x39 (0x588679 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank12]: frame #47: <unknown function> + 0x29d90 (0x14bea28e8d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank12]: frame #48: __libc_start_main + 0x80 (0x14bea28e8e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank12]: frame #49: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x58852e]
[rank12]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank15]: Traceback (most recent call last):
[rank15]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
[rank15]:     main(
[rank15]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 622, in main
[rank15]:     y, decode_latency, prefill_latency = generate(
[rank15]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank15]:     return func(*args, **kwargs)
[rank15]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 328, in generate
[rank15]:     send_recv(send_list=[], recv_list=[prefill_intermediate])
[rank15]:   File "/home/charlie/skip-residual/gpt-fast/gpt_fast/utils.py", line 436, in send_recv
[rank15]:     works = dist.batch_isend_irecv(ops)
[rank15]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2567, in batch_isend_irecv
[rank15]:     p2p_op.op(p2p_op.tensor, p2p_op.peer, p2p_op.group, p2p_op.tag)
[rank15]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2305, in irecv
[rank15]:     return pg.recv([tensor], group_src_rank, tag)
[rank15]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[rank15]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[rank15]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x14ad6396c106 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank15]: frame #1: <unknown function> + 0x62f51d8 (0x14ad531d11d8 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x367 (0x14ad531cdf57 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x2a (0x14ad531ce2da in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #4: c10d::TCPStore::get(std::string const&) + 0x7a (0x14ad531cf07a in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14ad5317c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14ad5317c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14ad5317c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14ad5317c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x14ad18bd681f in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank15]: frame #10: c10d::ProcessGroupNCCL::initNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x10c6 (0x14ad18be4386 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank15]: frame #11: c10d::ProcessGroupNCCL::recv(std::vector<at::Tensor, std::allocator<at::Tensor> >&, int, int) + 0x16c4 (0x14ad18c03404 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank15]: frame #12: <unknown function> + 0x62927f9 (0x14ad5316e7f9 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #13: <unknown function> + 0x629d1ea (0x14ad531791ea in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #14: <unknown function> + 0x58a83bb (0x14ad527843bb in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #15: <unknown function> + 0x58a5c39 (0x14ad52781c39 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #16: <unknown function> + 0x1aa3808 (0x14ad4e97f808 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #17: <unknown function> + 0x62a60c4 (0x14ad531820c4 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #18: <unknown function> + 0x62ab341 (0x14ad53187341 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank15]: frame #19: <unknown function> + 0xdfdbae (0x14ad62f81bae in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank15]: frame #20: <unknown function> + 0x4d9367 (0x14ad6265d367 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank15]: frame #21: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x4fdc87]
[rank15]: frame #22: _PyObject_MakeTpCall + 0x25b (0x4f741b in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #23: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x509cbf]
[rank15]: frame #24: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #25: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #26: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #27: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #28: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #29: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #30: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #31: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #32: PyObject_Call + 0xb8 (0x50a508 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #33: _PyEval_EvalFrameDefault + 0x2b79 (0x4f0c69 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #34: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #35: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #36: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #37: _PyEval_EvalFrameDefault + 0x31f (0x4ee40f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #38: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5950f2]
[rank15]: frame #39: PyEval_EvalCode + 0x87 (0x595037 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #40: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c5e67]
[rank15]: frame #41: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c0fb0]
[rank15]: frame #42: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x45970e]
[rank15]: frame #43: _PyRun_SimpleFileObject + 0x19f (0x5bb53f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #44: _PyRun_AnyFileObject + 0x43 (0x5bb2a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #45: Py_RunMain + 0x38d (0x5b805d in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #46: Py_BytesMain + 0x39 (0x588679 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank15]: frame #47: <unknown function> + 0x29d90 (0x14ad64876d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank15]: frame #48: __libc_start_main + 0x80 (0x14ad64876e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank15]: frame #49: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x58852e]
[rank15]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank10]: Traceback (most recent call last):
[rank10]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
[rank10]:     main(
[rank10]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 622, in main
[rank10]:     y, decode_latency, prefill_latency = generate(
[rank10]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank10]:     return func(*args, **kwargs)
[rank10]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 328, in generate
[rank10]:     send_recv(send_list=[], recv_list=[prefill_intermediate])
[rank10]:   File "/home/charlie/skip-residual/gpt-fast/gpt_fast/utils.py", line 436, in send_recv
[rank10]:     works = dist.batch_isend_irecv(ops)
[rank10]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2567, in batch_isend_irecv
[rank10]:     p2p_op.op(p2p_op.tensor, p2p_op.peer, p2p_op.group, p2p_op.tag)
[rank10]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2305, in irecv
[rank10]:     return pg.recv([tensor], group_src_rank, tag)
[rank10]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[rank10]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[rank10]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x15449c4f9106 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank10]: frame #1: <unknown function> + 0x62f51d8 (0x1544d7dd11d8 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x367 (0x1544d7dcdf57 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x2a (0x1544d7dce2da in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #4: c10d::TCPStore::get(std::string const&) + 0x7a (0x1544d7dcf07a in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1544d7d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1544d7d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1544d7d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1544d7d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x15449d7d681f in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank10]: frame #10: c10d::ProcessGroupNCCL::initNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x10c6 (0x15449d7e4386 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank10]: frame #11: c10d::ProcessGroupNCCL::recv(std::vector<at::Tensor, std::allocator<at::Tensor> >&, int, int) + 0x16c4 (0x15449d803404 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank10]: frame #12: <unknown function> + 0x62927f9 (0x1544d7d6e7f9 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #13: <unknown function> + 0x629d1ea (0x1544d7d791ea in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #14: <unknown function> + 0x58a83bb (0x1544d73843bb in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #15: <unknown function> + 0x58a5c39 (0x1544d7381c39 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #16: <unknown function> + 0x1aa3808 (0x1544d357f808 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #17: <unknown function> + 0x62a60c4 (0x1544d7d820c4 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #18: <unknown function> + 0x62ab341 (0x1544d7d87341 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank10]: frame #19: <unknown function> + 0xdfdbae (0x1544e7b81bae in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank10]: frame #20: <unknown function> + 0x4d9367 (0x1544e725d367 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank10]: frame #21: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x4fdc87]
[rank10]: frame #22: _PyObject_MakeTpCall + 0x25b (0x4f741b in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #23: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x509cbf]
[rank10]: frame #24: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #25: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #26: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #27: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #28: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #29: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #30: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #31: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #32: PyObject_Call + 0xb8 (0x50a508 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #33: _PyEval_EvalFrameDefault + 0x2b79 (0x4f0c69 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #34: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #35: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #36: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #37: _PyEval_EvalFrameDefault + 0x31f (0x4ee40f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #38: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5950f2]
[rank10]: frame #39: PyEval_EvalCode + 0x87 (0x595037 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #40: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c5e67]
[rank10]: frame #41: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c0fb0]
[rank10]: frame #42: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x45970e]
[rank10]: frame #43: _PyRun_SimpleFileObject + 0x19f (0x5bb53f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #44: _PyRun_AnyFileObject + 0x43 (0x5bb2a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #45: Py_RunMain + 0x38d (0x5b805d in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #46: Py_BytesMain + 0x39 (0x588679 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank10]: frame #47: <unknown function> + 0x29d90 (0x1544e9458d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank10]: frame #48: __libc_start_main + 0x80 (0x1544e9458e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank10]: frame #49: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x58852e]
[rank10]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank14]: Traceback (most recent call last):
[rank14]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
[rank14]:     main(
[rank14]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 622, in main
[rank14]:     y, decode_latency, prefill_latency = generate(
[rank14]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank14]:     return func(*args, **kwargs)
[rank14]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 328, in generate
[rank14]:     send_recv(send_list=[], recv_list=[prefill_intermediate])
[rank14]:   File "/home/charlie/skip-residual/gpt-fast/gpt_fast/utils.py", line 436, in send_recv
[rank14]:     works = dist.batch_isend_irecv(ops)
[rank14]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2567, in batch_isend_irecv
[rank14]:     p2p_op.op(p2p_op.tensor, p2p_op.peer, p2p_op.group, p2p_op.tag)
[rank14]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2305, in irecv
[rank14]:     return pg.recv([tensor], group_src_rank, tag)
[rank14]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[rank14]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[rank14]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x14727b2f9106 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank14]: frame #1: <unknown function> + 0x62f51d8 (0x1472b6bd11d8 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x367 (0x1472b6bcdf57 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x2a (0x1472b6bce2da in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #4: c10d::TCPStore::get(std::string const&) + 0x7a (0x1472b6bcf07a in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1472b6b7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1472b6b7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1472b6b7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x1472b6b7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x14727c5d681f in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank14]: frame #10: c10d::ProcessGroupNCCL::initNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x10c6 (0x14727c5e4386 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank14]: frame #11: c10d::ProcessGroupNCCL::recv(std::vector<at::Tensor, std::allocator<at::Tensor> >&, int, int) + 0x16c4 (0x14727c603404 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank14]: frame #12: <unknown function> + 0x62927f9 (0x1472b6b6e7f9 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #13: <unknown function> + 0x629d1ea (0x1472b6b791ea in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #14: <unknown function> + 0x58a83bb (0x1472b61843bb in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #15: <unknown function> + 0x58a5c39 (0x1472b6181c39 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #16: <unknown function> + 0x1aa3808 (0x1472b237f808 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #17: <unknown function> + 0x62a60c4 (0x1472b6b820c4 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #18: <unknown function> + 0x62ab341 (0x1472b6b87341 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank14]: frame #19: <unknown function> + 0xdfdbae (0x1472c6981bae in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank14]: frame #20: <unknown function> + 0x4d9367 (0x1472c605d367 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank14]: frame #21: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x4fdc87]
[rank14]: frame #22: _PyObject_MakeTpCall + 0x25b (0x4f741b in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #23: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x509cbf]
[rank14]: frame #24: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #25: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #26: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #27: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #28: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #29: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #30: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #31: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #32: PyObject_Call + 0xb8 (0x50a508 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #33: _PyEval_EvalFrameDefault + 0x2b79 (0x4f0c69 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #34: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #35: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #36: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #37: _PyEval_EvalFrameDefault + 0x31f (0x4ee40f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #38: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5950f2]
[rank14]: frame #39: PyEval_EvalCode + 0x87 (0x595037 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #40: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c5e67]
[rank14]: frame #41: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c0fb0]
[rank14]: frame #42: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x45970e]
[rank14]: frame #43: _PyRun_SimpleFileObject + 0x19f (0x5bb53f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #44: _PyRun_AnyFileObject + 0x43 (0x5bb2a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #45: Py_RunMain + 0x38d (0x5b805d in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #46: Py_BytesMain + 0x39 (0x588679 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank14]: frame #47: <unknown function> + 0x29d90 (0x1472c8256d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank14]: frame #48: __libc_start_main + 0x80 (0x1472c8256e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank14]: frame #49: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x58852e]
[rank14]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank13]: Traceback (most recent call last):
[rank13]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
[rank13]:     main(
[rank13]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 622, in main
[rank13]:     y, decode_latency, prefill_latency = generate(
[rank13]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank13]:     return func(*args, **kwargs)
[rank13]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 328, in generate
[rank13]:     send_recv(send_list=[], recv_list=[prefill_intermediate])
[rank13]:   File "/home/charlie/skip-residual/gpt-fast/gpt_fast/utils.py", line 436, in send_recv
[rank13]:     works = dist.batch_isend_irecv(ops)
[rank13]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2567, in batch_isend_irecv
[rank13]:     p2p_op.op(p2p_op.tensor, p2p_op.peer, p2p_op.group, p2p_op.tag)
[rank13]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2305, in irecv
[rank13]:     return pg.recv([tensor], group_src_rank, tag)
[rank13]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[rank13]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[rank13]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x14ea2f96c106 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank13]: frame #1: <unknown function> + 0x62f51d8 (0x14ea1f1d11d8 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x367 (0x14ea1f1cdf57 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x2a (0x14ea1f1ce2da in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #4: c10d::TCPStore::get(std::string const&) + 0x7a (0x14ea1f1cf07a in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14ea1f17c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14ea1f17c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14ea1f17c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14ea1f17c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x14e9e4bd681f in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank13]: frame #10: c10d::ProcessGroupNCCL::initNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x10c6 (0x14e9e4be4386 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank13]: frame #11: c10d::ProcessGroupNCCL::recv(std::vector<at::Tensor, std::allocator<at::Tensor> >&, int, int) + 0x16c4 (0x14e9e4c03404 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank13]: frame #12: <unknown function> + 0x62927f9 (0x14ea1f16e7f9 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #13: <unknown function> + 0x629d1ea (0x14ea1f1791ea in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #14: <unknown function> + 0x58a83bb (0x14ea1e7843bb in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #15: <unknown function> + 0x58a5c39 (0x14ea1e781c39 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #16: <unknown function> + 0x1aa3808 (0x14ea1a97f808 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #17: <unknown function> + 0x62a60c4 (0x14ea1f1820c4 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #18: <unknown function> + 0x62ab341 (0x14ea1f187341 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank13]: frame #19: <unknown function> + 0xdfdbae (0x14ea2ef81bae in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank13]: frame #20: <unknown function> + 0x4d9367 (0x14ea2e65d367 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank13]: frame #21: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x4fdc87]
[rank13]: frame #22: _PyObject_MakeTpCall + 0x25b (0x4f741b in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #23: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x509cbf]
[rank13]: frame #24: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #25: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #26: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #27: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #28: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #29: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #30: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #31: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #32: PyObject_Call + 0xb8 (0x50a508 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #33: _PyEval_EvalFrameDefault + 0x2b79 (0x4f0c69 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #34: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #35: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #36: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #37: _PyEval_EvalFrameDefault + 0x31f (0x4ee40f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #38: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5950f2]
[rank13]: frame #39: PyEval_EvalCode + 0x87 (0x595037 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #40: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c5e67]
[rank13]: frame #41: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c0fb0]
[rank13]: frame #42: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x45970e]
[rank13]: frame #43: _PyRun_SimpleFileObject + 0x19f (0x5bb53f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #44: _PyRun_AnyFileObject + 0x43 (0x5bb2a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #45: Py_RunMain + 0x38d (0x5b805d in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #46: Py_BytesMain + 0x39 (0x588679 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank13]: frame #47: <unknown function> + 0x29d90 (0x14ea308dcd90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank13]: frame #48: __libc_start_main + 0x80 (0x14ea308dce40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank13]: frame #49: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x58852e]
[rank13]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank9]: Traceback (most recent call last):
[rank9]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
[rank9]:     main(
[rank9]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 622, in main
[rank9]:     y, decode_latency, prefill_latency = generate(
[rank9]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank9]:     return func(*args, **kwargs)
[rank9]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 328, in generate
[rank9]:     send_recv(send_list=[], recv_list=[prefill_intermediate])
[rank9]:   File "/home/charlie/skip-residual/gpt-fast/gpt_fast/utils.py", line 436, in send_recv
[rank9]:     works = dist.batch_isend_irecv(ops)
[rank9]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2567, in batch_isend_irecv
[rank9]:     p2p_op.op(p2p_op.tensor, p2p_op.peer, p2p_op.group, p2p_op.tag)
[rank9]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2305, in irecv
[rank9]:     return pg.recv([tensor], group_src_rank, tag)
[rank9]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[rank9]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[rank9]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x14f49656c106 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank9]: frame #1: <unknown function> + 0x62f51d8 (0x14f485dd11d8 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x367 (0x14f485dcdf57 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x2a (0x14f485dce2da in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #4: c10d::TCPStore::get(std::string const&) + 0x7a (0x14f485dcf07a in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14f485d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14f485d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14f485d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14f485d7c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x14f44b7d681f in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank9]: frame #10: c10d::ProcessGroupNCCL::initNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x10c6 (0x14f44b7e4386 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank9]: frame #11: c10d::ProcessGroupNCCL::recv(std::vector<at::Tensor, std::allocator<at::Tensor> >&, int, int) + 0x16c4 (0x14f44b803404 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank9]: frame #12: <unknown function> + 0x62927f9 (0x14f485d6e7f9 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #13: <unknown function> + 0x629d1ea (0x14f485d791ea in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #14: <unknown function> + 0x58a83bb (0x14f4853843bb in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #15: <unknown function> + 0x58a5c39 (0x14f485381c39 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #16: <unknown function> + 0x1aa3808 (0x14f48157f808 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #17: <unknown function> + 0x62a60c4 (0x14f485d820c4 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #18: <unknown function> + 0x62ab341 (0x14f485d87341 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank9]: frame #19: <unknown function> + 0xdfdbae (0x14f495b81bae in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank9]: frame #20: <unknown function> + 0x4d9367 (0x14f49525d367 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank9]: frame #21: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x4fdc87]
[rank9]: frame #22: _PyObject_MakeTpCall + 0x25b (0x4f741b in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #23: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x509cbf]
[rank9]: frame #24: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #25: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #26: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #27: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #28: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #29: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #30: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #31: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #32: PyObject_Call + 0xb8 (0x50a508 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #33: _PyEval_EvalFrameDefault + 0x2b79 (0x4f0c69 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #34: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #35: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #36: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #37: _PyEval_EvalFrameDefault + 0x31f (0x4ee40f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #38: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5950f2]
[rank9]: frame #39: PyEval_EvalCode + 0x87 (0x595037 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #40: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c5e67]
[rank9]: frame #41: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c0fb0]
[rank9]: frame #42: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x45970e]
[rank9]: frame #43: _PyRun_SimpleFileObject + 0x19f (0x5bb53f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #44: _PyRun_AnyFileObject + 0x43 (0x5bb2a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #45: Py_RunMain + 0x38d (0x5b805d in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #46: Py_BytesMain + 0x39 (0x588679 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank9]: frame #47: <unknown function> + 0x29d90 (0x14f4974d3d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank9]: frame #48: __libc_start_main + 0x80 (0x14f4974d3e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank9]: frame #49: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x58852e]
[rank9]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank11]: Traceback (most recent call last):
[rank11]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
[rank11]:     main(
[rank11]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 622, in main
[rank11]:     y, decode_latency, prefill_latency = generate(
[rank11]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank11]:     return func(*args, **kwargs)
[rank11]:   File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 328, in generate
[rank11]:     send_recv(send_list=[], recv_list=[prefill_intermediate])
[rank11]:   File "/home/charlie/skip-residual/gpt-fast/gpt_fast/utils.py", line 436, in send_recv
[rank11]:     works = dist.batch_isend_irecv(ops)
[rank11]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2567, in batch_isend_irecv
[rank11]:     p2p_op.op(p2p_op.tensor, p2p_op.peer, p2p_op.group, p2p_op.tag)
[rank11]:   File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2305, in irecv
[rank11]:     return pg.recv([tensor], group_src_rank, tag)
[rank11]: torch.distributed.DistBackendError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[rank11]: Exception raised from recvBytes at ../torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[rank11]: frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x14d51916c106 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libc10.so)
[rank11]: frame #1: <unknown function> + 0x62f51d8 (0x14d5089d11d8 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #2: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x367 (0x14d5089cdf57 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #3: c10d::TCPStore::doGet(std::string const&) + 0x2a (0x14d5089ce2da in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #4: c10d::TCPStore::get(std::string const&) + 0x7a (0x14d5089cf07a in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #5: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14d50897c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #6: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14d50897c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #7: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14d50897c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #8: c10d::PrefixStore::get(std::string const&) + 0x31 (0x14d50897c4a1 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #9: c10d::ProcessGroupNCCL::broadcastUniqueNCCLID(ncclUniqueId*, bool, std::string const&, int) + 0xaf (0x14d4ce3d681f in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank11]: frame #10: c10d::ProcessGroupNCCL::initNCCLComm(std::string const&, c10::Device&, c10d::OpType, int, bool) + 0x10c6 (0x14d4ce3e4386 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank11]: frame #11: c10d::ProcessGroupNCCL::recv(std::vector<at::Tensor, std::allocator<at::Tensor> >&, int, int) + 0x16c4 (0x14d4ce403404 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
[rank11]: frame #12: <unknown function> + 0x62927f9 (0x14d50896e7f9 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #13: <unknown function> + 0x629d1ea (0x14d5089791ea in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #14: <unknown function> + 0x58a83bb (0x14d507f843bb in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #15: <unknown function> + 0x58a5c39 (0x14d507f81c39 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #16: <unknown function> + 0x1aa3808 (0x14d50417f808 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #17: <unknown function> + 0x62a60c4 (0x14d5089820c4 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #18: <unknown function> + 0x62ab341 (0x14d508987341 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[rank11]: frame #19: <unknown function> + 0xdfdbae (0x14d518781bae in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank11]: frame #20: <unknown function> + 0x4d9367 (0x14d517e5d367 in /home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[rank11]: frame #21: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x4fdc87]
[rank11]: frame #22: _PyObject_MakeTpCall + 0x25b (0x4f741b in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #23: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x509cbf]
[rank11]: frame #24: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #25: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #26: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #27: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #28: _PyEval_EvalFrameDefault + 0x4b26 (0x4f2c16 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #29: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #30: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #31: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #32: PyObject_Call + 0xb8 (0x50a508 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #33: _PyEval_EvalFrameDefault + 0x2b79 (0x4f0c69 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #34: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #35: _PyEval_EvalFrameDefault + 0x13b3 (0x4ef4a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #36: _PyFunction_Vectorcall + 0x6f (0x4fe0cf in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #37: _PyEval_EvalFrameDefault + 0x31f (0x4ee40f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #38: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5950f2]
[rank11]: frame #39: PyEval_EvalCode + 0x87 (0x595037 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #40: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c5e67]
[rank11]: frame #41: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x5c0fb0]
[rank11]: frame #42: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x45970e]
[rank11]: frame #43: _PyRun_SimpleFileObject + 0x19f (0x5bb53f in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #44: _PyRun_AnyFileObject + 0x43 (0x5bb2a3 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #45: Py_RunMain + 0x38d (0x5b805d in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #46: Py_BytesMain + 0x39 (0x588679 in /home/charlie/anaconda3/envs/gpt-fast/bin/python)
[rank11]: frame #47: <unknown function> + 0x29d90 (0x14d51a109d90 in /lib/x86_64-linux-gnu/libc.so.6)
[rank11]: frame #48: __libc_start_main + 0x80 (0x14d51a109e40 in /lib/x86_64-linux-gnu/libc.so.6)
[rank11]: frame #49: /home/charlie/anaconda3/envs/gpt-fast/bin/python() [0x58852e]
[rank11]: . This may indicate a possible application crash on rank 0 or a network set up issue.
[rank8]:[W1202 09:45:46.501220860 ProcessGroupNCCL.cpp:1374] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W1202 09:45:47.520000 2795967 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2796036 closing signal SIGTERM
W1202 09:45:47.521000 2795967 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2796037 closing signal SIGTERM
W1202 09:45:47.521000 2795967 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2796039 closing signal SIGTERM
W1202 09:45:47.521000 2795967 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2796040 closing signal SIGTERM
W1202 09:45:47.522000 2795967 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2796041 closing signal SIGTERM
W1202 09:45:47.528000 2795967 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2796042 closing signal SIGTERM
W1202 09:45:47.531000 2795967 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2796043 closing signal SIGTERM
E1202 09:45:48.218000 2795967 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 2 (pid: 2796038) of binary: /home/charlie/anaconda3/envs/gpt-fast/bin/python
Traceback (most recent call last):
  File "/home/charlie/anaconda3/envs/gpt-fast/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
benchmark.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-02_09:45:47
  host      : mk-xii-14.cloud.together.ai
  rank      : 10 (local_rank: 2)
  exitcode  : 1 (pid: 2796038)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
